services:
  web:
    build: .
    entrypoint: /usr/bin/docker-entrypoint
    command: ["/usr/bin/docker-entrypoint"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
