version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
# - deploy:
# filters:
#     branches:
#      only:
#       - main
#requires:
# - build
jobs:
  build:
    working_directory: ~/starTrekApp
    docker:
      - image: cimg/ruby:3.3.5-node

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}

      - run:
          name: install-bundle
          command: bundle install
      - run:
          name: install-yarn
          command: yarn install
      - run:
          name: setup-database
          command: bundle exec rake db:create

      - run:
          name: load-database-schema
          command: bundle exec rake db:schema:load

      - run:
          name: run-rubocop (linting)
          command: bundle exec rubocop

      - run:
          name: run-brakeman
          command: bundle exec brakeman

      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vender/bundle
deploy:
  docker:
    - image: cimg/ruby:3.3.5-node
  steps:
    - run:
        name: deploy-application
        command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@EC2_PUBLIC_DNS "rm -rf starTrekApp/; git clone https://github.com/mmNCI/starTrekApp.git; source starTrekApp/deploy.sh"
