version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

# - deploy:
# filters:
#     branches:
#      only:
#       - main
#requires:
# - build
jobs:
  build:
    working_directory: ~/starTrekApp
    docker:
      - image: cimg/ruby:3.3.5-node

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}

      - run:
          name: install-bundle
          command: bundle install
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vender/bundle
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
  test:
    working_directory: ~/starTrekApp
    docker:
      - image: cimg/ruby:3.3.5-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-v1-{{checksum "Gemfile.lock"}}
      - run:
          name: install-bundle
          command: bundle install
      - run:
          name: install-yarn
          command: yarn install
      - run:
          name: setup-database
          command: bundle exec rails db:create db:migrate
      - run:
          name: migrate-database
          command: bundle exec rails db:migrate

      - run:
          name: run-rubocop (linting)
          command: bundle exec rubocop

      - run:
          name: run-brakeman
          command: bundle exec brakeman

      - run:
          name: run-test-suite
          command: bundle exec rails test
  deploy:
    docker:
      - image: cimg/ruby:3.3.5-node
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@EC2_PUBLIC_DNS "rm -rf starTrekApp/; git clone https://github.com/mmNCI/starTrekApp.git; source starTrekApp/deploy.sh"
